name: Update ECR Image in Values YAML

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

env:
  ECR_REPOSITORY: nexus-repo
  AWS_REGION: eu-west-1
  VALUES_FILE: nexus-application/values.yaml  # Path to your values.yaml file
  OTHER_REPO: coforge-nexus/helmcharts  # Replace with your target repository

jobs:
  update-deployment:
    name: Build, Push Image, and Update Values YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Current Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get Commit Hash and Timestamp
        id: vars
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, Tag, and Push Docker Image to ECR
        run: |
          IMAGE_TAG=${{ env.commit_hash }}-${{ env.timestamp }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout the Other Repository (Helm Charts)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.OTHER_REPO }}
          token: ${{ secrets.MY_GITHUB_PAT }}

      - name: Update Values YAML with New Image
        run: |
          IMAGE_TAG=${{ env.commit_hash }}-${{ env.timestamp }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          sed -i "s|repository: .*|repository: $ECR_REGISTRY/$ECR_REPOSITORY|; s|tag: .*|tag: $IMAGE_TAG|" ${{ env.VALUES_FILE }}

      - name: Commit and Push Changes
        run: |
          git config user.name "Ubhaskar-coforge"
          git config user.email "Gandam.manikantha@coforge.com"
          git add ${{ env.VALUES_FILE }}
          git commit -m "Update values.yaml with new image tag $IMAGE_TAG"
          git push
