name: Update ECR Image in Deployment YAML

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # Required for requesting the JWT
  contents: write  # Required for actions/checkout
  actions: write   # Required for actions

env:
  APP_NAME: nexus-application  # Application name for tagging
  ECR_REPOSITORY: nexus-repo
  AWS_REGION: eu-west-1
  DEPLOYMENT_FILE: manifests/deployment.yaml  # Path to your deployment file
  OTHER_REPO: coforge-nexus/snyk-eks  # Replace with your target repository

jobs:
  update-deployment:
    name: Build, Push Image, and Update Deployment YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get the Current Version from ECR
        id: get-current-version
        run: |
          VERSION=$(aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY }} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
          if [[ "$VERSION" == "None" ]]; then
            VERSION="0"
          fi
          echo "version_number=$((VERSION+1))" >> $GITHUB_ENV

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.APP_NAME }}-v${{ env.version_number }}  # Tag format: nexus-application-vX
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update deployment.yaml with New Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.APP_NAME }}-v${{ env.version_number }}
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}  # Use your token from secrets
        run: |
          # Checkout the other repository
          git clone https://github.com/${{ env.OTHER_REPO }} other-repo
          cd other-repo

          # Update the deployment.yaml file with the new image
          sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" ${{ env.DEPLOYMENT_FILE }}
          
          # Commit the changes
          git config --local user.email "Gandam.manikantha@coforge.com"
          git config --local user.name "Ubhaskar-coforge"
          git add ${{ env.DEPLOYMENT_FILE }}
          git commit -m "Update deployment.yaml with new image tag $IMAGE_TAG"
          
          # Push the changes using custom token
          git push https://$MY_GITHUB_PAT:x-oauth-basic@github.com/${{ env.OTHER_REPO }}.git
