name: Update ECR Image in Values YAML

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

env:
  ECR_REPOSITORY: nexus-repo
  AWS_REGION: eu-west-1
  VALUES_FILE: nexus-application/values.yaml
  TARGET_REPO: coforge-nexus/helmcharts
  VERSION: v1  # Change this to v2, v3, etc., as needed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.ECR_REPOSITORY }}:${{ env.VERSION }}
        run: |
          docker build -t $IMAGE_TAG -f docker/Dockerfile .
          docker push $IMAGE_TAG

      - name: Update values.yaml and Push to Target Repo
        env:
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          git clone https://$MY_GITHUB_PAT@github.com/${{ env.TARGET_REPO }} target-repo
          sed -i "s|repository: .*|repository: $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}|; s|tag: .*|tag: ${{ env.VERSION }}|" target-repo/${{ env.VALUES_FILE }}
          cd target-repo
          git config --local user.email "Gandam.manikantha@coforge.com"
          git config --local user.name "Ubhaskar-coforge"
          git commit -am "Update values.yaml with new image tag ${{ env.VERSION }}"
          git push
