name: Deploy to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # Required for requesting the JWT
  contents: write  # Grant write access to push changes

env:
  ECR_REPOSITORY: nexus-repo
  AWS_REGION: eu-west-1    

jobs:
  build:
    name: Build, Push Image, and Update Deployment in snyk-eks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout snyk-eks repository
        uses: actions/checkout@v2
        with:
          repository: coforge-nexus/snyk-eks
          path: snyk-eks

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s#image: .*#image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.commit_hash }}-${{ env.timestamp }}#" snyk-eks/manifests/deployment.yaml

      - name: Commit and push updated deployment.yaml to snyk-eks repo
        run: |
          git config --local user.email "Gandam.manikantha@coforge.com"
          git config --local user.name "Ubhaskar-coforge"
          git add snyk-eks/manifests/deployment.yaml
          git commit -m "Update deployment.yaml with new image tag $IMAGE_TAG"
          git push https://github.com/coforge-nexus/snyk-eks.git HEAD:main
