name: Build and Push Helm Chart to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-1  # Ensure you set the correct AWS region here

      - name: Log in to ECR for Docker and Helm
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Package Helm Chart
        run: |
          # Package the Helm chart
          helm package path/to/chart -d packaged_charts

      - name: Tag and Push Helm Chart to ECR
        env:
          ECR_REGISTRY: 123456789012.dkr.ecr.eu-west-1.amazonaws.com
          ECR_HELM_REPO: helm-test-chart
        run: |
          # Use Helm to authenticate and save the Helm chart as an OCI artifact
          helm registry login -u AWS --password-stdin $ECR_REGISTRY

          # Save and push the Helm chart
          helm chart save packaged_charts/helm-test-chart-0.1.0.tgz oci://$ECR_REGISTRY/$ECR_HELM_REPO:0.1.0
          helm chart push oci://$ECR_REGISTRY/$ECR_HELM_REPO:0.1.0

      - name: Verify Helm Chart in ECR
        run: |
          aws ecr describe-images --repository-name $ECR_HELM_REPO --region eu-west-1
