name: Build, Push Docker Image, and Push Helm Chart to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

env:
  ECR_DOCKER_REPOSITORY: nexus-repo  # ECR repo for Docker images
  ECR_HELM_REPOSITORY: helm-test-chart  # ECR repo for Helm charts
  AWS_REGION: eu-west-1
  VALUES_FILE: nexus-application/values.yaml
  OTHER_REPO: coforge-nexus/helmcharts

jobs:
  update-deployment:
    name: Build, Push Docker Image, Push Helm Chart, and Update values.yaml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_DOCKER_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_DOCKER_REPOSITORY:$IMAGE_TAG

      - name: Package Helm Chart
        run: |
          helm package nexus-application --version "0.1.0-${{ env.commit_hash }}" --app-version "0.1.0-${{ env.commit_hash }}"
          mv "nexus-application-0.1.0-${{ env.commit_hash }}.tgz" helm-chart.tgz

      - name: Push Helm Chart to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws ecr create-repository --repository-name $ECR_HELM_REPOSITORY --region $AWS_REGION || true
          aws ecr put-image --repository-name $ECR_HELM_REPOSITORY \
            --image-tag "0.1.0-${{ env.commit_hash }}" \
            --image-manifest file://helm-chart.tgz

      - name: Update values.yaml with New Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}  # Use your token from secrets
        run: |
          # Checkout the other repository with the token
          git clone https://$MY_GITHUB_PAT:x-oauth-basic@github.com/${{ env.OTHER_REPO }}.git other-repo
          cd other-repo
          # Update the values.yaml file with the new Docker image
          sed -i "s|repository: .*|repository: $ECR_REGISTRY/$ECR_DOCKER_REPOSITORY|" ${{ env.VALUES_FILE }}
          sed -i "s|tag: .*|tag: $IMAGE_TAG|" ${{ env.VALUES_FILE }}

          # Commit the changes
          git config --local user.email "Gandam.manikantha@coforge.com"
          git config --local user.name "Ubhaskar-coforge"
          git add ${{ env.VALUES_FILE }}
          git commit -m "Update values.yaml with new Docker image tag $IMAGE_TAG"

          # Push the changes using the token
          git push https://$MY_GITHUB_PAT:x-oauth-basic@github.com/${{ env.OTHER_REPO }}.git
