name: Deploy to ECR and Update deployment.yaml

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout

env:
  ECR_REPOSITORY: nexus-repo
  AWS_REGION: eu-west-1
  TARGET_REPO: coforge-nexus/snyk-eks
  TARGET_PATH: manifests/deployment.yaml

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: main

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          COMMIT_HASH: ${{ steps.get-commit-hash.outputs.commit_hash }}
          TIMESTAMP: ${{ steps.get-timestamp.outputs.timestamp }}
        run: |
          # Ensure both COMMIT_HASH and TIMESTAMP are not empty
          if [ -z "$COMMIT_HASH" ]; then echo "COMMIT_HASH is empty"; exit 1; fi
          if [ -z "$TIMESTAMP" ]; then echo "TIMESTAMP is empty"; exit 1; fi
          
          IMAGE_TAG=$COMMIT_HASH-$TIMESTAMP
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i 's|image: .*|image: '"${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.COMMIT_HASH }}-${{ env.TIMESTAMP }}"'|' ${{ env.TARGET_PATH }}

      - name: Commit and push changes to deployment.yaml
        run: |
          git config --local user.email "Gandam.manikantha@coforge.com"
          git config --local user.name "Ubhaskar-coforge"
          git add ${{ env.TARGET_PATH }}
          git commit -m "Update deployment.yaml with new image tag $IMAGE_TAG"
          git push
