name: Update ECR Image and Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: nexus-repo  # Change this to your Docker ECR repository
  ECR_HELM_REPO: 442426854264.dkr.ecr.eu-west-1.amazonaws.com/nexus-helm-repo
  CHART_NAME: my-helm-chart  # Change this to your Helm chart name
  CHART_VERSION: 0.1.0  # Define your chart version
  VALUES_FILE: nexus-application/values.yaml  # Path to your values.yaml file

jobs:
  build-and-deploy:
    name: Build Docker Image, Package Helm Chart, and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # Your IAM role for GitHub Actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: List Files for Debugging
        run: |
          echo "Listing files in the root directory:"
          ls -la
          echo "Listing files in the my-helm-chart directory:"
          ls -la path/to/my-helm-chart  # Update this path as necessary

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
        run: |
          # Ensure the Dockerfile path is correct. Update if necessary.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Package Helm Chart
        run: |
          helm package path/to/my-helm-chart --version ${{ env.CHART_VERSION }}  # Update this path

      - name: Push Helm Chart to ECR
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          helm push ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz oci://${{ env.ECR_HELM_REPO }}
