name: Update ECR Image in Values YAML

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

env:
  ECR_REPOSITORY: nexus-repo
  AWS_REGION: eu-west-1
  VALUES_FILE: nexus-application/values.yaml
  TARGET_REPO: coforge-nexus/helmcharts

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Get commit hash and timestamp
        id: vars
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} -f docker/Dockerfile .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Update values.yaml and Push to Target Repo
        env:
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          git clone https://$MY_GITHUB_PAT@github.com/${{ env.TARGET_REPO }} target-repo
          sed -i "s|repository: .*|repository: $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}|; s|tag: .*|tag: $IMAGE_TAG|" target-repo/${{ env.VALUES_FILE }}
          cd target-repo
          git config --local user.email "Gandam.manikantha@coforge.com"
          git config --local user.name "Ubhaskar-coforge"
          git commit -am "Update values.yaml with new image tag $IMAGE_TAG"
          git push
