name: Update ECR Image in values.yaml and Push Helm Chart to ECR
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

env:
  ECR_REPOSITORY: nexus-repo
  AWS_REGION: eu-west-1
  VALUES_FILE: nexus-application/values.yaml
  OTHER_REPO: coforge-nexus/helmcharts
  HELM_CHART_DIR: helm-test-chart  # <-- Define the Helm chart directory here
  HELM_ECR_REPOSITORY: 442426854264.dkr.ecr.eu-west-1.amazonaws.com/helm-test-chart

jobs:
  update-deployment:
    name: Build, Push Image, Update values.yaml, and Push Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update values.yaml with New Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          git clone https://$MY_GITHUB_PAT:x-oauth-basic@github.com/${{ env.OTHER_REPO }}.git other-repo
          cd other-repo
          
          sed -i "s|repository: .*|repository: $ECR_REGISTRY/$ECR_REPOSITORY|" ${{ env.VALUES_FILE }}
          sed -i "s|tag: .*|tag: $IMAGE_TAG|" ${{ env.VALUES_FILE }}

          git config --local user.email "Gandam.manikantha@coforge.com"
          git config --local user.name "Ubhaskar-coforge"
          git add ${{ env.VALUES_FILE }}
          git commit -m "Update values.yaml with new image tag $IMAGE_TAG"

          git push https://$MY_GITHUB_PAT:x-oauth-basic@github.com/${{ env.OTHER_REPO }}.git

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm Chart Directory
        run: |
          if [ ! -d "${{ env.HELM_CHART_DIR }}" ]; then
            echo "Helm chart directory ${{ env.HELM_CHART_DIR }} not found."
            exit 1
          fi

      - name: Log in to ECR for Helm
        env:
          HELM_ECR_REPOSITORY: ${{ env.HELM_ECR_REPOSITORY }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | helm registry login --username AWS --password-stdin $HELM_ECR_REPOSITORY

      - name: Package Helm Chart
        run: |
          helm package ${{ env.HELM_CHART_DIR }}

      - name: Push Helm Chart to ECR
        env:
          HELM_ECR_REPOSITORY: ${{ env.HELM_ECR_REPOSITORY }}
        run: |
          helm push ${{ env.HELM_CHART_DIR }}-0.1.0.tgz oci://$HELM_ECR_REPOSITORY
